### ISSUE TITLE
LICENSE file

### ISSUE THREAD

**Issue by langston-barrett** [mckeankylej/avl#2]
Looking good, Kyle :) Might want to add a LICENSE file. Here's what I normally tell people:

From http://choosealicense.com/no-license :

> You’ll have to check with your own legal counsel regarding your particular project, but generally speaking, the absence of a license means that default copyright laws apply. This means that you retain all rights to your source code and that nobody else may reproduce, distribute, or create derivative works from your work.

**Comment by aljce** [comment]
Thanks for noticing I normally use MIT but I forgot. fixed in: d5bc2ac032306320b3259ba262054b2167284992
